### ISSUE TITLE
Error when entering text-only coverage

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineFeatures#84]
The error that shows up is:

> Mysqli statement execute error : Incorrect integer value: '' for column 'zoom' at row 1

And the traceback:

```
#0 /Users/err8n/neatline/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /Users/err8n/neatline/plugins/NeatlineFeatures/models/Table/Table_NeatlineFeature.php(346): Zend_Db_Statement->execute(Array)
#2 /Users/err8n/neatline/plugins/NeatlineFeatures/models/Table/Table_NeatlineFeature.php(389): Table_NeatlineFeature->createFeatures(Object(Item), Array)
#3 /Users/err8n/neatline/plugins/NeatlineFeatures/NeatlineFeaturesPlugin.php(261): Table_NeatlineFeature->updateFeatures(Object(Item), Array)
#4 [internal function]: NeatlineFeaturesPlugin->hookAfterSaveItem(Array)
#5 /Users/err8n/neatline/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#6 /Users/err8n/neatline/application/libraries/Omeka/Record/AbstractRecord.php(298): Omeka_Plugin_Broker->callHook('after_save_item', Array)
#7 /Users/err8n/neatline/application/libraries/Omeka/Record/AbstractRecord.php(550): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#8 /Users/err8n/neatline/application/libraries/Omeka/Controller/AbstractActionController.php(144): Omeka_Record_AbstractRecord->save(false)
#9 /Users/err8n/neatline/application/controllers/ItemsController.php(149): Omeka_Controller_AbstractActionController->addAction()
#10 /Users/err8n/neatline/application/libraries/Zend/Controller/Action.php(516): ItemsController->addAction()
#11 /Users/err8n/neatline/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#12 /Users/err8n/neatline/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /Users/err8n/neatline/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#14 /Users/err8n/neatline/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#15 /Users/err8n/neatline/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#16 /Users/err8n/neatline/admin/index.php(28): Omeka_Application->run()
#17 {main}
```

And for the POST data:

```
Content-Disposition: form-data; name="OpenLayers.Control.LayerSwitcher_6_baseLayers"

OpenStreetMap
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Coverage"

Coverage
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][free]\""

something
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][geo]"


-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][zoom]"


-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][center_lon]"


-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][center_lat]"


-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][base_layer]"

osm
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][text]"

||||osm
something
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][html]"

0
-----------------------------14717089242952395221403421684
Content-Disposition: form-data; name="Elements[38][0][mapon]"

0
```

**Comment by erochest** [comment]
I suspect this may have the do with the version of something. I can't reproduce this in my VM, but it does happen on my Mac. We can still be defensive about it, though.
